service: cheeseday

provider:
  name: aws
  runtime: nodejs4.3
  stage: prod
  region: eu-west-1

plugins:
  - serverless-offline

functions:
  bot:
    handler: messenger.index
    memorySize: 1024
    timeout: 10
    events:
      - http:
          path: webhook
          method: get
          integration: lambda
      - http:
          path: webhook
          method: post
          integration: lambda
  cron:
    handler: task.index
    memorySize: 1024
    timeout: 10
    events:
      - schedule: cron(0 * ? * 3 *) # Every tuesday
      # cron(Minutes Hours Day-of-month Month Day-of-week Year)
